In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df=pd.read_excel('flight_price.xlsx')
df.head(2)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [4]:
df['Date']=df['Date_of_Journey'].str.split("/").str[0]
df['Month']=df['Date_of_Journey'].str.split("/").str[1]
df['Year']=df['Date_of_Journey'].str.split("/").str[2]
df.head(2)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,03,2019
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,05,2019

In [ ]:
df['Date']=df['Date'].astype(int)
df['Month']=df['Month'].astype(int)
df["Year"]=df['Year'].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
 11  Date             10683 non-null  int64
 12  Month            10683 non-null  int64
 13  Year             10683 non-null  int64
dtypes: int64(4), object(10)
memory usage: 1.1+ MB

In [6]:
df['Dep_hour']=df['Dep_Time'].str.split(':').str[0]
df['Dep_min']=df['Dep_Time'].str.split(":").str[1]
df['Dep_hour']=df['Dep_hour'].astype(int)
df['Dep_min']=df['Dep_min'].astype(int)
df.drop('Dep_Time',axis=1,inplace=True)
df.head(2)

,Airline,Date_of_Journey,Source,Destination,Route,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Dep_hour,Dep_min
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019,22,20
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,13:15,7h 25m,2 stops,No info,7662,1,5,2019,5,50

In [7]:
df.head(2)

,Airline,Date_of_Journey,Source,Destination,Route,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Dep_hour,Dep_min
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019,22,20
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,13:15,7h 25m,2 stops,No info,7662,1,5,2019,5,50

In [8]:
df['Total_Stops'].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops'],
      dtype=object)

In [9]:
df['Total_Stops']=df["Total_Stops"].map({"non-stop": 0,
    "1 stop": 1,
    "2 stops": 2,
    "3 stops": 3,
    "4 stops": 4})

In [10]:
df.head(2)

,Airline,Date_of_Journey,Source,Destination,Route,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Dep_hour,Dep_min
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,01:10 22 Mar,2h 50m,0.0,No info,3897,24,3,2019,22,20
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,13:15,7h 25m,2.0,No info,7662,1,5,2019,5,50

In [11]:
df['Additional_Info'].unique()

array(['No info', 'In-flight meal not included',
       'No check-in baggage included', '1 Short layover', 'No Info',
       '1 Long layover', 'Change airports', 'Business class',
       'Red-eye flight', '2 Long layover'], dtype=object)

In [ ]:
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder()
df1=pd.DataFrame(encoder.fit_transform(df[["Additional_Info"]]).toarray(),columns=encoder.get_feature_names_out())

In [13]:
df.head(2)

,Airline,Date_of_Journey,Source,Destination,Route,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Dep_hour,Dep_min
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,01:10 22 Mar,2h 50m,0.0,No info,3897,24,3,2019,22,20
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,13:15,7h 25m,2.0,No info,7662,1,5,2019,5,50

In [14]:
df2=pd.concat([df,df1],axis=1)
df2.head(2)

,Airline,Date_of_Journey,Source,Destination,Route,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,...,Additional_Info_1 Long layover,Additional_Info_1 Short layover,Additional_Info_2 Long layover,Additional_Info_Business class,Additional_Info_Change airports,Additional_Info_In-flight meal not included,Additional_Info_No Info,Additional_Info_No check-in baggage included,Additional_Info_No info,Additional_Info_Red-eye flight
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,01:10 22 Mar,2h 50m,0.0,No info,3897,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,13:15,7h 25m,2.0,No info,7662,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [15]:
df3=pd.DataFrame(encoder.fit_transform(df[["Airline","Source","Destination"]]).toarray(),columns=encoder.get_feature_names_out())
df4=pd.concat([df2,df3],axis=1)
df4.head(2)

,Airline,Date_of_Journey,Source,Destination,Route,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,...,Source_Chennai,Source_Delhi,Source_Kolkata,Source_Mumbai,Destination_Banglore,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,01:10 22 Mar,2h 50m,0.0,No info,3897,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,13:15,7h 25m,2.0,No info,7662,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [16]:
df4.drop('Date_of_Journey',axis=1,inplace=True)

In [17]:
df4.head(2)

,Airline,Source,Destination,Route,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,...,Source_Chennai,Source_Delhi,Source_Kolkata,Source_Mumbai,Destination_Banglore,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi
0,IndiGo,Banglore,New Delhi,BLR → DEL,01:10 22 Mar,2h 50m,0.0,No info,3897,24,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,13:15,7h 25m,2.0,No info,7662,1,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [18]:
df4['Arrival_Time']=df['Arrival_Time'].apply(lambda x:x.split(' ')[0])

In [19]:
df4['Arrival_hour']=df4['Arrival_Time'].str.split(":").str[0]
df4['Arrival_min']=df4['Arrival_Time'].str.split(":").str[1]

In [20]:

df4.head(2)

,Airline,Source,Destination,Route,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,...,Source_Kolkata,Source_Mumbai,Destination_Banglore,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi,Arrival_hour,Arrival_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,01:10,2h 50m,0.0,No info,3897,24,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,01,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,13:15,7h 25m,2.0,No info,7662,1,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,13,15

In [21]:
df4.drop("Arrival_Time",axis=1,inplace=True)

In [22]:
df4.head(2)

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,...,Source_Kolkata,Source_Mumbai,Destination_Banglore,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi,Arrival_hour,Arrival_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,0.0,No info,3897,24,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,01,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2.0,No info,7662,1,5,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,13,15

In [23]:
df4.drop("Additional_Info",axis=1,inplace=True)

In [24]:
df4.head(2)

,Airline,Source,Destination,Route,Duration,Total_Stops,Price,Date,Month,Year,...,Source_Kolkata,Source_Mumbai,Destination_Banglore,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi,Arrival_hour,Arrival_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,0.0,3897,24,3,2019,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,01,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2.0,7662,1,5,2019,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,13,15

In [25]:
df4["Duration_Hour"] = df4["Duration"].str.extract(r"(\d+)h").fillna(0).astype(int)

df4["Duration_Min"] = df4["Duration"].str.extract(r"(\d+)m").fillna(0).astype(int)

In [26]:
df4.head(5)

,Airline,Source,Destination,Route,Duration,Total_Stops,Price,Date,Month,Year,...,Destination_Banglore,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi,Arrival_hour,Arrival_min,Duration_Hour,Duration_Min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,0.0,3897,24,3,2019,...,0.0,0.0,0.0,0.0,0.0,1.0,01,10,2,50
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2.0,7662,1,5,2019,...,1.0,0.0,0.0,0.0,0.0,0.0,13,15,7,25
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2.0,13882,9,6,2019,...,0.0,1.0,0.0,0.0,0.0,0.0,04,25,19,0
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1.0,6218,12,5,2019,...,1.0,0.0,0.0,0.0,0.0,0.0,23,30,5,25
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1.0,13302,1,3,2019,...,0.0,0.0,0.0,0.0,0.0,1.0,21,35,4,45

In [27]:
df4.drop('Duration',axis=1,inplace=True)

In [28]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 48 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Airline                                       10683 non-null  object
 1   Source                                        10683 non-null  object
 2   Destination                                   10683 non-null  object
 3   Route                                         10682 non-null  object
 4   Total_Stops                                   10682 non-null  float64
 5   Price                                         10683 non-null  int64
 6   Date                                          10683 non-null  int64
 7   Month                                         10683 non-null  int64
 8   Year                                          10683 non-null  int64
 9   Dep_hour                                      10683 non-null  int64
 10  Dep_min                                       10683 non-null  int64
 11  Additional_Info_1 Long layover                10683 non-null  float64
 12  Additional_Info_1 Short layover               10683 non-null  float64
 13  Additional_Info_2 Long layover                10683 non-null  float64
 14  Additional_Info_Business class                10683 non-null  float64
 15  Additional_Info_Change airports               10683 non-null  float64
 16  Additional_Info_In-flight meal not included   10683 non-null  float64
 17  Additional_Info_No Info                       10683 non-null  float64
 18  Additional_Info_No check-in baggage included  10683 non-null  float64
 19  Additional_Info_No info                       10683 non-null  float64
 20  Additional_Info_Red-eye flight                10683 non-null  float64
 21  Airline_Air Asia                              10683 non-null  float64
 22  Airline_Air India                             10683 non-null  float64
 23  Airline_GoAir                                 10683 non-null  float64
 24  Airline_IndiGo                                10683 non-null  float64
 25  Airline_Jet Airways                           10683 non-null  float64
 26  Airline_Jet Airways Business                  10683 non-null  float64
 27  Airline_Multiple carriers                     10683 non-null  float64
 28  Airline_Multiple carriers Premium economy     10683 non-null  float64
 29  Airline_SpiceJet                              10683 non-null  float64
 30  Airline_Trujet                                10683 non-null  float64
 31  Airline_Vistara                               10683 non-null  float64
 32  Airline_Vistara Premium economy               10683 non-null  float64
 33  Source_Banglore                               10683 non-null  float64
 34  Source_Chennai                                10683 non-null  float64
 35  Source_Delhi                                  10683 non-null  float64
 36  Source_Kolkata                                10683 non-null  float64
 37  Source_Mumbai                                 10683 non-null  float64
 38  Destination_Banglore                          10683 non-null  float64
 39  Destination_Cochin                            10683 non-null  float64
 40  Destination_Delhi                             10683 non-null  float64
 41  Destination_Hyderabad                         10683 non-null  float64
 42  Destination_Kolkata                           10683 non-null  float64
 43  Destination_New Delhi                         10683 non-null  float64
 44  Arrival_hour                                  10683 non-null  object
 45  Arrival_min                                   10683 non-null  object
 46  Duration_Hour                                 10683 non-null  int64
 47  Duration_Min                                  10683 non-null  int64
dtypes: float64(34), int64(8), object(6)
memory usage: 3.9+ MB

In [29]:
df4['Total_Duration']=df4['Duration_Hour'] * 60 + df4['Duration_Min'].astype(int)

In [30]:
df4.head(2)

,Airline,Source,Destination,Route,Total_Stops,Price,Date,Month,Year,Dep_hour,...,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi,Arrival_hour,Arrival_min,Duration_Hour,Duration_Min,Total_Duration
0,IndiGo,Banglore,New Delhi,BLR → DEL,0.0,3897,24,3,2019,22,...,0.0,0.0,0.0,0.0,1.0,01,10,2,50,170
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2.0,7662,1,5,2019,5,...,0.0,0.0,0.0,0.0,0.0,13,15,7,25,445

In [31]:
df4.drop("Airline",axis=1,inplace=True)

In [32]:
df4.drop("Duration_Hour",axis=1,inplace=True)
df4.drop("Duration_Min",axis=1,inplace=True)

In [33]:
df4.drop("Source",axis=1,inplace=True)
df4.drop("Destination",axis=1,inplace=True)

In [34]:
df4.head(5)

,Route,Total_Stops,Price,Date,Month,Year,Dep_hour,Dep_min,Additional_Info_1 Long layover,Additional_Info_1 Short layover,...,Source_Mumbai,Destination_Banglore,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi,Arrival_hour,Arrival_min,Total_Duration
0,BLR → DEL,0.0,3897,24,3,2019,22,20,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,01,10,170
1,CCU → IXR → BBI → BLR,2.0,7662,1,5,2019,5,50,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,13,15,445
2,DEL → LKO → BOM → COK,2.0,13882,9,6,2019,9,25,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,04,25,1140
3,CCU → NAG → BLR,1.0,6218,12,5,2019,18,5,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,23,30,325
4,BLR → NAG → DEL,1.0,13302,1,3,2019,16,50,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,21,35,285

In [35]:
df4.shape

(10683, 44)

In [36]:
df.shape

(10683, 15)