In [1]:
import pandas as pd
import numpy as np

In [2]:
student_data=[
  [1, 15],
  [2, 11],
  [7, 11],
  [4, 20]
]
df=pd.DataFrame(student_data)

In [3]:
df=pd.DataFrame(student_data).rename(columns={0:"area",1:"population"})

In [4]:
df.head()

   area  population
0     1          15
1     2          11
2     7          11
3     4          20

In [5]:
df.loc[df['area']>2 | (df['population']>15)]

   area  population
1     2          11
2     7          11
3     4          20

In [6]:
df['area']=df['area'].replace({7:10})

In [7]:
df

   area  population
0     1          15
1     2          11
2    10          11
3     4          20

In [8]:
df.sort_values("area")

   area  population
0     1          15
1     2          11
3     4          20
2    10          11

In [9]:
df1=df.loc[(df['population']==11)]

In [10]:
df1

   area  population
1     2          11
2    10          11

In [12]:
df1=df1.rename(columns={'population':'popp'})

In [13]:
df1

   area  popp
1     2    11
2    10    11